// Code generated by go-swagger; DO NOT EDIT.

// Copyright SecureKey Technologies Inc. All Rights Reserved.
//
// SPDX-License-Identifier: Apache-2.0
//

package protect

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/trustbloc/ace/pkg/client/gatekeeper/models"
)

// PostProtectReader is a Reader for the PostProtect structure.
type PostProtectReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostProtectReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostProtectOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPostProtectOK creates a PostProtectOK with default headers values
func NewPostProtectOK() *PostProtectOK {
	return &PostProtectOK{}
}

/* PostProtectOK describes a response with status code 200, with default header values.

Data protected
*/
type PostProtectOK struct {
	Payload *models.ProtectResp
}

func (o *PostProtectOK) Error() string {
	return fmt.Sprintf("[POST /protect][%d] postProtectOK  %+v", 200, o.Payload)
}
func (o *PostProtectOK) GetPayload() *models.ProtectResp {
	return o.Payload
}

func (o *PostProtectOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ProtectResp)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
