// Code generated by go-swagger; DO NOT EDIT.

// Copyright SecureKey Technologies Inc. All Rights Reserved.
//
// SPDX-License-Identifier: Apache-2.0
//

package protect

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/trustbloc/ace/pkg/client/gatekeeper/models"
)

// NewPostProtectParams creates a new PostProtectParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostProtectParams() *PostProtectParams {
	return &PostProtectParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostProtectParamsWithTimeout creates a new PostProtectParams object
// with the ability to set a timeout on a request.
func NewPostProtectParamsWithTimeout(timeout time.Duration) *PostProtectParams {
	return &PostProtectParams{
		timeout: timeout,
	}
}

// NewPostProtectParamsWithContext creates a new PostProtectParams object
// with the ability to set a context for a request.
func NewPostProtectParamsWithContext(ctx context.Context) *PostProtectParams {
	return &PostProtectParams{
		Context: ctx,
	}
}

// NewPostProtectParamsWithHTTPClient creates a new PostProtectParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostProtectParamsWithHTTPClient(client *http.Client) *PostProtectParams {
	return &PostProtectParams{
		HTTPClient: client,
	}
}

/* PostProtectParams contains all the parameters to send to the API endpoint
   for the post protect operation.

   Typically these are written to a http.Request.
*/
type PostProtectParams struct {

	/* Body.

	   Data to protect and protection policy
	*/
	Body *models.ProtectReq

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post protect params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostProtectParams) WithDefaults() *PostProtectParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post protect params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostProtectParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post protect params
func (o *PostProtectParams) WithTimeout(timeout time.Duration) *PostProtectParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post protect params
func (o *PostProtectParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post protect params
func (o *PostProtectParams) WithContext(ctx context.Context) *PostProtectParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post protect params
func (o *PostProtectParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post protect params
func (o *PostProtectParams) WithHTTPClient(client *http.Client) *PostProtectParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post protect params
func (o *PostProtectParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post protect params
func (o *PostProtectParams) WithBody(body *models.ProtectReq) *PostProtectParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post protect params
func (o *PostProtectParams) SetBody(body *models.ProtectReq) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostProtectParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
