// Code generated by go-swagger; DO NOT EDIT.

// Copyright SecureKey Technologies Inc. All Rights Reserved.
//
// SPDX-License-Identifier: Apache-2.0
//

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ProtectResp protect resp
//
// swagger:model ProtectResp
type ProtectResp struct {

	// did
	Did string `json:"did,omitempty"`
}

// Validate validates this protect resp
func (m *ProtectResp) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this protect resp based on context it is used
func (m *ProtectResp) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ProtectResp) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ProtectResp) UnmarshalBinary(b []byte) error {
	var res ProtectResp
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
